# -*- coding: utf-8 -*-
"""HW04_R_Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bsGgXqpwsC3LNlPmeeIDoVigs8039--X
"""

# Game: Rock Scissors Paper
# Create Open Game function
# Computer move is random
# Tell a player's accumulated points in each rounds


Open_Game <- function() {
  actions <- c("Rock", "Paper", "Scissors", "Quit Game")
  win <- 0
  loss <- 0
  tie <- 0
  
  while (TRUE) {
    player_move <- as.numeric(readline("Choose your move: Rock[1], Paper[2], Scissors[3], Quit Game[4]: "))
    if (player_move == 4) {
      cat("See ya if you want!")
      break
    }
    
    player_move <- actions[player_move]
    computer_move <- actions[sample(1:3, 1)]
    
    if (player_move == computer_move) {
      tie <- tie + 1
    } else if (player_move == "Rock" & computer_move == "Paper") {
      loss <- loss + 1
    } else if (player_move == "Paper" & computer_move == "Scissors") {
      loss <- loss + 1
    } else if (player_move == "Scissors" & computer_move == "Rock") {
      loss <- loss + 1
    } else {
      win <- win + 1
    }
    
    cat("Player Move:", player_move, "\n")
    cat("Computer Move:", computer_move, "\n")
    cat(win, loss, tie)
    print(data.frame(win,loss,tie),row.names = FALSE)
  }
}